- edit: https://github.com/flancian/garden/edit/main/{path}
  format: foam
  protocol: git
  target: garden/flancian
  url: https://github.com/flancian/garden.git
  web: https://github.com/flancian/garden/blob/main/{path}
- edit: https://garden.bouncepaw.com/edit/{slug}
  format: mycorrhiza
  target: garden/melanocarpa
  url: https://github.com/bouncepaw/melanocarpa.git
  web: https://garden.bouncepaw.com/hypha/{slug}
- format: mycorrhiza
  target: garden/betula-site
  url: https://git.sr.ht/~bouncepaw/betula-site
  web: https://betula.mycorrhiza.wiki/{slug}
- format: mycorrhiza
  target: garden/bouncepaw-betula
  url: https://git.agor.ai/bouncepaw/betulagora-bouncepaw
- format: mycorrhiza
  target: garden/flancian-betula
  url: https://git.agor.ai/bouncepaw/betulagora-flancian
- format: jekyll
  protocol: git
  target: garden/bmann
  url: https://github.com/bmann/bmcgarden.git
- format: foam
  target: garden/s5bug
  url: https://gitdab.com/s/garden.git
- format: obsidian
  target: garden/jonathan
  url: https://github.com/JonathanLorand/AgoraGarden
- format: foam
  target: garden/luciana
  url: https://github.com/malfattti/garden.git
- format: roam2agora
  target: garden/ArghZero
  url: https://github.com/arghzero/agora-garden.git
- format: foam
  target: garden/olofl
  url: https://github.com/oloflindholm/garden
- format: foam
  target: garden/KGBicheno
  url: https://github.com/KGBicheno/KGB_Agora
- format: foam
  target: garden/dr_kvj
  url: https://github.com/drkvj/agora
- format: foam
  target: garden/bbchase
  url: https://github.com/bbchase/agora
- format: roam
  target: garden/houshuang
  url: https://github.com/houshuang/stian-notes.git
- format: foam
  target: garden/tilda
  url: https://github.com/tilda/agora
- format: foam
  target: garden/binnyva
  url: https://github.com/binnyva/DZG
- format: foam
  target: garden/vera
  url: https://git.anagora.org/vera/notes.git
- format: logseq
  target: garden/vera-logseq
  url: https://github.com/fuck-capitalism/logseq.git
- format: foam
  target: garden/law
  url: https://github.com/zavislak/law.md.git
- format: obsidian
  target: garden/rusp
  url: https://github.com/Rusp1972/vault
- format: foam
  target: garden/seph
  url: https://github.com/bathrobe/sephagora.git
- format: foam
  target: garden/jakeisnt
  url: https://github.com/jakeisnt/wiki.git
- format: foam
  target: garden/mwt
  url: https://github.com/mwt/agora.git
- format: foam
  target: garden/plantey
  url: https://github.com/Ejipuh/Plantey-Garden
- format: foam
  target: garden/ankostis
  url: https://github.com/ankostis/Garden
- format: foam
  target: garden/danielarmengolaltayo
  url: https://github.com/danielarmengolaltayo/agora
- edit: https://gitlab.com/ngm/commonplace-agora/-/edit/master/{path}
  format: ox-agora
  target: garden/neil
  url: https://gitlab.com/ngm/commonplace-agora.git
  web: https://commonplace.doubleloop.net/{slug}
- format: stoa
  target: garden/patterning
  url: https://github.com/JonathanLorand/patterning.git
- format: jekyll
  target: garden/moa-party
  url: https://gitlab.com/fedstoa/moaparty/moaparty.com.git
- format: org2md
  target: garden/karlicoss
  url: https://github.com/karlicoss/exobrain-md.git
- format: obsidian
  target: garden/volt4ire
  url: https://github.com/volt4ire/agora
- format: ox-agora
  target: garden/ryan
  url: https://github.com/rfaulhaber/roam
- format: foam
  target: garden/gyuri
  url: https://github.com/gyuri-lajos/gyuri
- format: foam
  target: garden/unrival
  url: https://github.com/unrival-protocol/protocol
- format: foam
  target: garden/forshaper
  url: https://github.com/ray-dorai/ray-dorai.github.io
- format: foam
  target: garden/j0lms
  url: https://codeberg.org/j0lms/notes-md
- format: fedwiki
  target: garden/vera.wiki.anagora.org
  url: http://vera.wiki.anagora.org
- format: obsidian
  protocol: git
  support: https://flattr.com/@evan
  target: garden/evan
  url: https://git.sr.ht/~boehs/oasis.git
- format: obsidian
  target: garden/xiq
  url: https://github.com/TheExGenesis/agora
- format: obsidian
  target: garden/JackKausch
  url: https://github.com/JackKausch/vaults
- edit: https://doc.anagora.org/{slug}?edit
  format: stoa
  protocol: git
  target: stoa/doc.anagora.org
  url: https://github.com/flancia-coop/doc.anagora.org
- edit: https://github.com/flancian/flancia/edit/main/{path}
  format: nikola
  protocol: git
  support: https://flancia.org
  target: garden/flancia.org
  url: https://github.com/flancian/flancia
- format: tiddlywiki
  target: garden/maya
  url: https://teapot.systems/maya/mayagora.git
- format: quartz
  target: garden/darlim
  url: https://github.com/hdarlim/quartz
- format: obsidian
  target: garden/protopian
  url: https://git.anagora.org/ProtopianFox/Agora-Garden.git
- format: foam
  target: garden/blindpill
  url: https://github.com/blindpill/notes.git
- format: foam
  target: garden/the_one
  url: https://github.com/mnenoff/flancia01
- format: hugo
  target: garden/wilde-at-heart
  url: https://github.com/jlcolbert/jlcolbert.github.io.git
- edit: https://github.com/OpenGlobalMind/rel8-wiki/edit/master/{path}
  format: obsidian
  target: garden/rel8
  url: https://github.com/OpenGlobalMind/rel8-wiki
  web: https://wiki.rel8.dev/scalingsynthesis.com/{path}
- edit: https://github.com/classicrob/quartz/edit/master/{path}
  format: quartz
  target: garden/scalingsynthesis
  url: https://github.com/classicrob/quartz
  web: https://scalingsynthesis.com/{path}
- format: ox-agora
  target: garden/khinsen
  url: https://github.com/khinsen/agora-garden
- format: foam
  target: garden/tekakutli
  url: https://github.com/tekakutli/agora-garden
- format: org
  target: garden/tekakutli-org
  url: https://codeberg.org/tekakutli/neuralnomicon
- format: mycorrhiza
  target: garden/vera-mycorrhiza
  url: https://git.anagora.org/vera/myconotes.git
- format: obsidian
  target: garden/jayu
  url: https://github.com/jayu-eleutheria/agora-digital-garden.git
- format: communecter
  target: garden/communecter
  url: https://gitlab.adullact.net/pixelhumain/codoc
- format: org
  target: garden/oceane
  url: https://git.sr.ht/~oceane/connaissances-personnelles-au-format-markdown
- edit: https://mau.dev/andreijiroh-dev/wiki/edit/main/{path}
  format: foam
  target: garden/ajhalili2006
  url: https://mau.dev/andreijiroh-dev/wiki
  web: https://wiki.andreijiroh.xyz/{path}
- edit: https://wiki.andreijiroh.xyz/migrate/agora?path={path}&edit=1
  format: obsidian
  target: garden/ajhalili2006-old
  url: https://mau.dev/ajhalili2006-archive/digital-garden.git
  web: https://wiki.andreijiroh.xyz/migrate/agora?path={path}
- format: foam
  target: garden/vera-journal
  url: https://github.com/codegod100/daily.git
- format: logseq
  target: garden/sparql
  url: https://github.com/kvistgaard/sparql.git
- format: quartz
  target: garden/matthieuG
  url: https://github.com/lagouttiere-crypto/matthieu-gaudeau.github.io.git
- format: markdown
  target: garden/agora-server
  url: https://github.com/flancian/agora-server
- format: markdown
  target: garden/flaneur
  url: https://git.anagora.org/flaneur/garden.git
  web: https://git.anagora.org/flaneur/garden.git
- format: markdown
  target: garden/sgmk
  url: https://git.anagora.org/sgmk/garden
  web: https://git.anagora.org/sgmk/garden
- format: markdown
  target: garden/jennaalexja
  url: https://git.anagora.org/jennaalexja/garden
  web: https://git.anagora.org/jennaalexja/garden
