#!/bin/bash -e
# (this should be run from the root of the repo: util/reset)
# Before adding, you need to run add once (same command line but with add).
set -e
cd $HOME/agora
rm -rf garden
mkdir -p garden
cd garden
git clone https://github.com/flancian/garden.git flancian 
git clone https://gitdab.com/s/garden.git s5bug 
git clone https://github.com/JonathanLorand/AgoraGarden jonathan 
git clone https://github.com/malfattti/garden.git luciana 
git clone https://github.com/arghzero/agora-garden.git ArghZero 
git clone https://github.com/oloflindholm/garden olofl 
git clone https://github.com/KGBicheno/KGB_Agora KGBicheno 
